import io
import json
import os
import subprocess
import tempfile
import time
import wave
from pathlib import Path
from typing import Optional


class PiperTTS:
	"""Lightweight Piper-based TTS utility for navigation commands."""

	DEFAULT_SAMPLE_RATE = 22050

	def __init__(
		self,
		piper_executable: str,
		voice_model_path: str,
		voice_config_path: Optional[str] = None,
		output_dir: Optional[str] = None,
	):
		self.piper_executable = Path(piper_executable)
		self.voice_model_path = Path(voice_model_path)
		self.voice_config_path = Path(voice_config_path) if voice_config_path else None

		if output_dir is None:
			default_dir = Path(__file__).resolve().parent / "audio_outputs"
			self.output_dir = default_dir
		else:
			self.output_dir = Path(output_dir)

		self.output_dir.mkdir(parents=True, exist_ok=True)
		self._validate_paths()

	def _validate_paths(self) -> None:
		if not self.piper_executable.exists():
			raise FileNotFoundError(f"Piper executable not found: {self.piper_executable}")
		if not self.voice_model_path.exists():
			raise FileNotFoundError(f"Piper voice model not found: {self.voice_model_path}")
		if self.voice_config_path is not None and not self.voice_config_path.exists():
			raise FileNotFoundError(f"Piper voice config not found: {self.voice_config_path}")

	@staticmethod
	def _normalize_text(text: str) -> str:
		cleaned = " ".join((text or "").strip().split())
		if not cleaned:
			raise ValueError("Navigation command text is empty.")
		return cleaned

	@staticmethod
	def _require_windows(message: str) -> None:
		if os.name != "nt":
			raise RuntimeError(message)

	def _build_command(self, output_file: Optional[str] = None, output_raw: bool = False):
		cmd = [
			str(self.piper_executable),
			"--model",
			str(self.voice_model_path),
		]
		if self.voice_config_path is not None:
			cmd.extend(["--config", str(self.voice_config_path)])
		if output_file is not None:
			cmd.extend(["--output_file", output_file])
		if output_raw:
			cmd.append("--output_raw")
		return cmd

	def _run_bytes(self, cmd, text: str):
		return subprocess.run(
			cmd,
			input=text.encode("utf-8"),
			capture_output=True,
			check=False,
		)

	def _sample_rate(self) -> int:
		if self.voice_config_path is None:
			return self.DEFAULT_SAMPLE_RATE
		try:
			with open(self.voice_config_path, "r", encoding="utf-8") as f:
				cfg = json.load(f)
			return int(cfg.get("audio", {}).get("sample_rate", self.DEFAULT_SAMPLE_RATE))
		except Exception:
			return self.DEFAULT_SAMPLE_RATE

	def _pcm_to_wav_bytes(self, pcm_bytes: bytes) -> bytes:
		buffer = io.BytesIO()
		with wave.open(buffer, "wb") as wav_file:
			wav_file.setnchannels(1)
			wav_file.setsampwidth(2)
			wav_file.setframerate(self._sample_rate())
			wav_file.writeframes(pcm_bytes)
		return buffer.getvalue()

	@staticmethod
	def _is_valid_wav_bytes(wav_bytes: bytes) -> bool:
		if not wav_bytes or wav_bytes[:4] != b"RIFF":
			return False
		try:
			with wave.open(io.BytesIO(wav_bytes), "rb") as wav_file:
				channels = wav_file.getnchannels()
				width = wav_file.getsampwidth()
				frames = wav_file.getnframes()
				return channels >= 1 and width in (1, 2, 3, 4) and frames > 0
		except Exception:
			return False

	def synthesize_wav_bytes(self, text: str) -> bytes:
		"""Generate WAV bytes with a quality-first path.

		Primary path uses Piper's file WAV output (historically most stable quality),
		then reads the generated bytes back into memory.
		"""
		command_text = self._normalize_text(text)

		# Attempt 1 (quality-first): synthesize to a temporary WAV file then read bytes.
		tmp_wav_path = None
		try:
			fd, tmp_wav_path = tempfile.mkstemp(suffix=".wav", dir=str(self.output_dir))
			os.close(fd)
			self.synthesize(command_text, output_wav_path=tmp_wav_path, play_audio=False)
			with open(tmp_wav_path, "rb") as f:
				wav_bytes = f.read()
			if self._is_valid_wav_bytes(wav_bytes):
				return wav_bytes
		except Exception:
			pass
		finally:
			if tmp_wav_path and os.path.exists(tmp_wav_path):
				try:
					os.remove(tmp_wav_path)
				except OSError:
					pass

		# Attempt 2: Ask Piper to write WAV bytes to stdout.
		result_wav = self._run_bytes(self._build_command(output_file="-"), command_text)
		if result_wav.returncode == 0 and self._is_valid_wav_bytes(result_wav.stdout):
			return result_wav.stdout

		# Attempt 3: Raw PCM fallback wrapped into WAV.
		result_raw = self._run_bytes(self._build_command(output_raw=True), command_text)
		if result_raw.returncode != 0:
			raise RuntimeError(
				"Piper in-memory synthesis failed. "
				f"stderr={result_raw.stderr.decode(errors='ignore').strip()}"
			)
		wav_bytes = self._pcm_to_wav_bytes(result_raw.stdout)
		if not self._is_valid_wav_bytes(wav_bytes):
			raise RuntimeError("Generated in-memory WAV bytes are invalid.")
		return wav_bytes

	def speak_direct(self, text: str) -> None:
		"""Speak directly from generated binary audio without saving WAV file."""
		self._require_windows("Direct in-memory playback helper currently supports Windows only.")
		wav_bytes = self.synthesize_wav_bytes(text)
		self.play_bytes(wav_bytes)

	def speak_stream(self, text: str) -> None:
		"""Stream Piper raw PCM directly to speaker with sounddevice.

		This avoids WAV file IO and uses the correct sample rate from model config.
		"""
		command_text = self._normalize_text(text)
		try:
			import numpy as np  # pylint: disable=import-outside-toplevel
			import sounddevice as sd  # pylint: disable=import-outside-toplevel
		except ImportError as exc:
			raise RuntimeError(
				"sounddevice and numpy are required for raw stream playback. "
				"Install with: pip install sounddevice numpy"
			) from exc

		proc = subprocess.Popen(
			self._build_command(output_raw=True),
			stdin=subprocess.PIPE,
			stdout=subprocess.PIPE,
			stderr=subprocess.PIPE,
		)
		stdout_bytes, stderr_bytes = proc.communicate(input=command_text.encode("utf-8"))

		if proc.returncode != 0:
			raise RuntimeError(
				"Piper raw stream failed. "
				f"stderr={stderr_bytes.decode(errors='ignore').strip()}"
			)

		audio_data = np.frombuffer(stdout_bytes, dtype=np.int16)
		if audio_data.size == 0:
			raise RuntimeError("Piper returned empty raw audio buffer.")

		sd.play(audio_data, self._sample_rate())
		sd.wait()

	def speak_direct_safe(self, text: str, fallback_play_audio: bool = True) -> str:
		"""Try direct memory playback, fallback to file synthesis if needed.

		Returns playback mode: 'raw-stream', 'direct-memory', or 'file-fallback'.
		"""
		try:
			self.speak_stream(text)
			return "raw-stream"
		except Exception:
			pass

		try:
			self.speak_direct(text)
			return "direct-memory"
		except Exception:
			self.synthesize(text, play_audio=fallback_play_audio)
			return "file-fallback"

	def synthesize(
		self,
		text: str,
		output_wav_path: Optional[str] = None,
		play_audio: bool = False,
	) -> str:
		"""Generate speech from text and optionally play it.

		Returns absolute output WAV path.
		"""
		command_text = self._normalize_text(text)

		if output_wav_path is None:
			ts = int(time.time() * 1000)
			wav_path = self.output_dir / f"nav_command_{ts}.wav"
		else:
			wav_path = Path(output_wav_path)
			wav_path.parent.mkdir(parents=True, exist_ok=True)

		result = subprocess.run(
			self._build_command(output_file=str(wav_path)),
			input=command_text,
			capture_output=True,
			text=True,
			check=False,
		)
		if result.returncode != 0:
			raise RuntimeError(
				"Piper synthesis failed. "
				f"stdout={result.stdout.strip()} stderr={result.stderr.strip()}"
			)

		if play_audio:
			self.play(str(wav_path))

		return str(wav_path.resolve())

	@staticmethod
	def play(wav_path: str) -> None:
		"""Play a WAV file on Windows using winsound."""
		PiperTTS._require_windows("Audio playback helper currently supports Windows only.")

		import winsound  # pylint: disable=import-outside-toplevel

		winsound.PlaySound(str(Path(wav_path).resolve()), winsound.SND_FILENAME)

	@staticmethod
	def play_bytes(wav_bytes: bytes) -> None:
		"""Play in-memory WAV bytes on Windows using winsound."""
		PiperTTS._require_windows("In-memory playback helper currently supports Windows only.")

		import winsound  # pylint: disable=import-outside-toplevel

		winsound.PlaySound(wav_bytes, winsound.SND_MEMORY)


if __name__ == "__main__":
	cwd = os.getcwd()

	piper_exe = os.path.abspath(os.path.join(cwd, "app", "piper", "piper.exe"))
	voice_model = os.path.abspath(os.path.join(cwd, "app", "piper_voices", "en_US-amy-medium.onnx"))
	voice_config = os.path.abspath(os.path.join(cwd, "app", "piper_voices", "en_US-amy-medium.onnx.json"))

	tts = PiperTTS(
		piper_executable=piper_exe,
		voice_model_path=voice_model,
		voice_config_path=voice_config,
	)
	wav_file = tts.synthesize("Clear path on your left. Turn left.", play_audio=False)
	print(f"Generated: {wav_file}")
