DEFAULT_SHORTEN_TTS_COMMANDS = True

# Quality-first defaults for cleaner synthesis/playback.
DEFAULT_TTS_USE_IN_MEMORY = True
DEFAULT_TTS_SAVE_AUDIO_ARTIFACTS = True
DEFAULT_TTS_ENABLE_PHRASE_CACHE = True
DEFAULT_TTS_PHRASE_CACHE_MAXSIZE = 128

DEFAULT_TTS_PLAY_AUDIO = True
DEFAULT_TTS_DIRECT_PLAYBACK = False
DEFAULT_TTS_SPEAK_ONCE_PER_EXECUTION = False
DEFAULT_TTS_SPEAK_ON_COMMAND_CHANGE = True
DEFAULT_TTS_MIN_INTERVAL_SECONDS = 1.2
DEFAULT_TTS_QUEUE_MAXSIZE = 5
DEFAULT_TTS_USE_PROCESS_WORKER = True
DEFAULT_TTS_LATEST_ONLY_QUEUE = True
DEFAULT_TTS_PREWARM_COMMON_PHRASES = True
DEFAULT_TTS_USE_RUNTIME_SYNTHESIS = False
DEFAULT_TTS_ENABLE_PRIORITY_PREEMPT = True